server:
  port: 8761

eureka:
  server:
    enable-self-preservation: true
  instance:
    hostname: eureka-service-1
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/