spring:
  profiles:
    active: e2
#  application:
#    name: sword-laboratory-eureka-service

eureka:
  server:
    enable-self-preservation: true
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/